# Generated by Django 4.1 on 2023-01-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0004_alter_course_unique_together_remove_grade_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="folder", name="language",),
    ]
